<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>VOIDTUNE.WinUI</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x64;arm64</Platforms>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <EnableMsixTooling>true</EnableMsixTooling>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>VOIDTUNE</AssemblyName>
    <DefaultLanguage>en-US</DefaultLanguage>
    <Version>0.8.18</Version>
    <FileVersion>0.8.18.0</FileVersion>
    <AssemblyVersion>0.8.18.0</AssemblyVersion>
    <Product>VOIDTUNE</Product>
    <Company>otzpt</Company>
    <ApplicationIcon>Assets\voidtune.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.6.*" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.*" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.*" />
    <PackageReference Include="System.Management" Version="8.*" />
  </ItemGroup>

</Project>
